services:
  web:
    build: .
    ports:
      - "5000-5100:5000"
    volumes:
      - .:/app   # reload the app on code changes
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: python app.py
